- name: Disable Kerb-Pre Auth for william.marlowe
  win_shell: Import-Module ActiveDirectory; Set-ADAccountControl -Identity william.marlowe -DoesNotRequirePreAuth $true
  args:
    executable: powershell
