- name: (dauntless admin impersonation) Register script to run on boot using Task Scheduler
  community.windows.win_scheduled_task:
    name: Impersonation
    description: "Do not delete"
    actions:
      - path: C:\Windows\System32\calc.exe
    triggers:
      - type: boot
        delay: P0Y0M0DT0H1M0S
        enabled: true
    run_level: highest
    logon_type: password
    state: present
    username: 'SEVENSEAS\{{ username }}'
    password: "{{ password }}"
    enabled: true
    author: SEVENSEAS\murtogg.smith
    compatability: 4
    multiple_instances: 2
    restart_count: 9
    restart_interval: P0Y0M0DT0H1M0S
    start_when_available: true
    allow_demand_start: true

# Give Impersonation privileges to reginald.biggleton
- name: Give Impersonation privs to reginald.biggleton
  ansible.windows.win_user_right:
    name: SeImpersonatePrivilege
    users: 
     - sevenseas.local\reginald.biggleton
    action: add

- name: Restart Dauntless to launch impersonation script
  ansible.windows.win_reboot: