- name: Change Host name      #ansible-galaxy collection install ansible.windows
    ansible.windows.win_hostname:
      name: Interceptor
    register: res 

- name: Reboot
  ansible.windows.win_reboot:
  when: res.reboot_required
