# Give Impersonation privileges to reginald.biggleton
- name: Give Impersonation privs to reginald.biggleton
  ansible.windows.win_user_right:
    name: SeImpersonatePrivilege
    users: 
     - sevenseas.local\reginald.biggleton
    action: add

# Give GenericAll privs to Amelia over Admirals
- name: Grant Amelia.Doppler GenericAll over Admirals group
  ansible.windows.win_shell: |
    $srcobj = (Get-ADUser -Identity "amelia.doppler").sid
    $dstobj = (Get-ADGroup -Identity "Admirals").DistinguishedName
    $right = "GenericAll"

    $ADObject = [ADSI]("LDAP://" + $dstobj)
    $adRights = [System.DirectoryServices.ActiveDirectoryRights]$right
    $type = [System.Security.AccessControl.AccessControlType] "Allow"
    $inheritanceType = [System.DirectoryServices.ActiveDirectorySecurityInheritance] "All"
    $ACE = New-Object System.DirectoryServices.ActiveDirectoryAccessRule $srcobj,$adRights,$type,$inheritanceType
    $ADObject.psbase.ObjectSecurity.AddAccessRule($ACE)
    $ADObject.psbase.commitchanges()

# Give ForceChangePassword privs to Amelia over James.Norrington user
#- name: Grant Amelia.Doppler ForceChangePassword over Admirals
#  ansible.windows.win_shell: |
#    $srcobj = (Get-ADUser -Identity "amelia.doppler").sid
#    $dstobj = (Get-ADUser -Identity "james.norrington").DistinguishedName
#
#    $ADObject = [ADSI]("LDAP://" + $dstobj)
#    $guid = "00299570-246d-11d0-a768-00aa006e0529" 
#    $type = [System.Security.AccessControl.AccessControlType] "Allow"
#    $inheritanceType = [System.DirectoryServices.ActiveDirectorySecurityInheritance] "All"
#    $ACE = New-Object System.DirectoryServices.ExtendedRightAccessRule $srcobj,$type,$guid,$inheritanceType
#    $ADObject.psbase.ObjectSecurity.AddAccessRule($ACE)
#    $ADObject.psbase.commitchanges()