- name: This DC shall henceforth be known as PortRoyal!      #ansible-galaxy collection install ansible.windows
  ansible.windows.win_hostname:
    name: PortRoyal-DC
  register: res 

- name: Reboot
  ansible.windows.win_reboot:
  when: res.reboot_required
