# Give GenericAll privs to Amelia over Admirals
- name: Copying setacl script over to PortRoyal
  ansible.windows.win_copy:
    src: files/setacl.ps1
    dest: C:\Windows\Temp\setacl.ps1

- name: Running setacl script on PortRoyal
  ansible.windows.win_command: C:\Windows\Temp\setacl.ps1