#Function will disable UAC, Firewall and windows defender through registry key manipulation
    - name: Disable UAC, Firewall, and Defender
      ansible.windows.win_regedit:
        path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'
        name: EnableLUA
        data: 0
        type: dword

    - name: Disable Defender Service
      ansible.windows.win_regedit:
        path: 'HKLM:\System\CurrentControlSet\Services\SecurityHealthService'
        name: Start
        data: 4
        type: dword

    - name: Disable Defender Anti-Spyware
      ansible.windows.win_regedit:
        path: 'HKLM:\Software\Policies\Microsoft\Windows Defender'
        name: DisableAntiSpyware
        data: 1
        type: dword

    - name: Disable Defender Anti-Virus
      ansible.windows.win_regedit:
        path: 'HKLM:\Software\Policies\Microsoft\Windows Defender'
        name: DisableAntiVirus
        data: 1
        type: dword

    - name: Disable Defender MpEngine
      ansible.windows.win_regedit:
        path: 'HKLM:\Software\Policies\Microsoft\Windows Defender\MpEngine'
        name: MpEnablePus
        data: 0
        type: dword

    - name: Disable Defender Behavior Monitoring
      ansible.windows.win_regedit:
        path: 'HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection'
        name: DisableBehaviorMonitoring
        data: 1
        type: dword

    - name: Disable Defender IOAV Protection
      ansible.windows.win_regedit:
        path: 'HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection'
        name: DisableIOAVProtection
        data: 1
        type: dword

    - name: Disable Defender On-Access Protection
      ansible.windows.win_regedit:
        path: 'HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection'
        name: DisableOnAccessProtection
        data: 1
        type: dword

    - name: Disable Defender Real-Time Monitoring
      ansible.windows.win_regedit:
        path: 'HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection'
        name: DisableRealtimeMonitoring
        data: 1
        type: dword

    - name: Disable Defender Scan on Real-Time Enable
      ansible.windows.win_regedit:
        path: 'HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection'
        name: DisableScanOnRealtimeEnable
        data: 1
        type: dword

    - name: Disable Defender Script Scanning
      ansible.windows.win_regedit:
        path: 'HKLM:\Software\Policies\Microsoft\Windows Defender\Real-Time Protection'
        name: DisableScriptScanning
        data: 1
        type: dword

    - name: Disable Defender Enhanced Notifications
      ansible.windows.win_regedit:
        path: 'HKLM:\Software\Policies\Microsoft\Windows Defender\Reporting'
        name: DisableEnhancedNotifications
        data: 1
        type: dword

    - name: Disable Defender Block at First Seen
      ansible.windows.win_regedit:
        path: 'HKLM:\Software\Policies\Microsoft\Windows Defender\SpyNet'
        name: DisableBlockAtFirstSeen
        data: 1
        type: dword

    - name: Disable Defender Spynet Reporting
      ansible.windows.win_regedit:
        path: 'HKLM:\Software\Policies\Microsoft\Windows Defender\SpyNet'
        name: SpynetReporting
        data: 0
        type: dword

    - name: Disable Defender Samples Consent
      ansible.windows.win_regedit:
        path: 'HKLM:\Software\Policies\Microsoft\Windows Defender\SpyNet'
        name: SubmitSamplesConsent
        data: 2
        type: dword

    - name: Disable Windows Defender Scheduled Tasks
      ansible.windows.win_regedit:
        path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run'
        name: "{{ item }}"
        data: ""
        type: string
      loop:
        - 'Windows Defender'
        - 'Windows Defender Scheduled Scan'
        - 'Windows Defender Verification'

    - name: Stop Windows Update Service
      ansible.windows.win_service:
        name: wuauserv
        state: stopped
        start_mode: disabled

    - name: Disable Windows Update
      ansible.windows.win_regedit:
        path: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU'
        name: NoAutoUpdate
        data: 1
        type: dword

    - name: Disable Remote UAC
      ansible.windows.win_regedit:
        path: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'
        name: LocalAccountTokenFilterPolicy
        data: 1
        type: dword

    - name: Enable ICMP Echo on IPv4 and IPv6
      community.windows.win_firewall_rule:
        name: "{{ item.name }}"
        protocol: "{{ item.protocol }}"
        dir: in
        action: allow
      loop:
        - { name: 'ICMP Allow incoming V4 echo request', protocol: icmpv4:8, any }
        - { name: 'ICMP Allow incoming V6 echo request', protocol: icmpv6:8, any }

    - name: Enable Network Discovery
      community.windows.win_firewall_rule:
        name: "{{ item.name }}"
        profile: "{{ item.profile }}"
        state: present
      loop:
        - { name: '@FirewallAPI.dll,-32752', profile: 'Private, Domain' }

    - name: Disable Windows Defender Firewalls
      community.windows.win_firewall:
        state: disabled
        profiles:
          - Domain
          - Public
          - Private
