- name: Create Active Directory users
  ansible.windows.win_user:
    fullname: "{{ item.first_name }} {{ item.last_name }}"
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    password_never_expires: true
    groups:
      - "{{ item.group }}"
      - Domain Users
    description: "{{ item.description }}"
    state: present
  loop: "{{ ad_users }}"

- name: Admiralize James Norrington
  microsoft.ad.group:
    name: Domain Admins
    scope: domainlocal
    members:
      add:
        - Admirals

#- name: Add Passwordless User
#  win_shell: net user "benjamin.clarke" /passwordreq:no /add /domain /comment:"Im too lazy for a password..." /expires:never /fullname:"Benjamin Clarke"
#  args:
#    executable: powershell

- name: Add passwordless user benjamin.clarke
  ansible.windows.win_user:
    name: benjamin.clarke
    password: 
    password_never_expires: true
    groups:
      - Domain Users
    description: "Im too lazy for a password"
    state: present

- name: Allow domain users to log on locally
  ansible.windows.win_user_right:
    name: SeInteractiveLogonRight
    users: BUILTIN\Users
    action: add

- name: Set Profiles
  community.windows.win_user_profile:
    username: "{{item.username}}"
  loop: "{{ ad_users }}"
