- name: Building PortRoyal...
  hosts: portroyal
  gather_facts: true
  roles:
  - role: NukeDefender
  - role: Remove_All_Updates
  - role: SetPortRoyalHostName
  - role: PromoteToDC
  - role: ConfigureADCS
  - role: SetTimeZone
  - role: EstablishRoyalShare
  - role: SetPasswordPolicy
  - role: RecruitNavySailors
  - role: KerberoastSailor
  - role: LLMNRPoisoning
  - role: ASREPRoast
  - role: AnonymousLDAPBind
  - role: EnableRDP

- name: Launching Dauntless...
  hosts: dauntless
  gather_facts: true
  roles:
  - role: NukeDefender
  - role: Remove_All_Updates
  - role: DomainJoinDauntless
  - role: PromoteMurtogg
  - role: TokenImpersonation
  - role: EnableRDP

- name: Launching Interceptor...
  hosts: interceptor
  gather_facts: true
  roles:
  - role: NukeDefender
  - role: Remove_All_Updates
  - role: DomainJoinInterceptor
  - role: PromoteMullroy
  - role: EnableRDP
