- name: Building PortRoyal...
  hosts: portroyal
  gather_facts: true
  roles:
  - role: NukeDefender
  - role: Remove_All_Updates
  - role: SetPortRoyalHostName
  - role: UpgradeToDC
  - role: ConfigureADCS
  - role: SetTimeZone

- name: Launching Dauntless...
  hosts: dauntless
  gather_facts: true
  roles:
  - role: NukeDefender
  - role: Remove_All_Updates
  - role: SetDauntlessHostName
  - role: DomainJoinDauntless

- name: Launching Interceptor...
  hosts: interceptor
  gather_facts: true
  roles:
  - role: NukeDefender
  - role: Remove_All_Updates
  - role: SetInterceptorHostName
  - role: DomainJoinInterceptor
