- name: Building PortRoyal...
  hosts: portroyal
  gather_facts: true
  roles:
  - role: NukeDefender
  - role: Remove_All_Updates
  - role: SetPortRoyalHostName
  - role: PromoteToDC
  - role: ConfigureADCS
  - role: SetTimeZone
  - role: EstablishRoyalShare
  - role: SetPasswordPolicy
  - role: OrganizeRoyalNavy
  - role: RecruitNavySailors
  - role: KerberoastSailor
  - role: LLMNRPoisoning
  - role: ASREPRoast
  - role: AnonymousLDAPBind
  - role: EnableRDP
  - role: QueenizeAmelia

- name: Launching Dauntless...
  hosts: dauntless
  gather_facts: true
  roles:
  - role: NukeDefender
  - role: Remove_All_Updates
  - role: DomainJoinDauntless
  
- name: Promoting Murtogg on Dauntless
  hosts: admin-dauntless
  gather_facts: true
  roles:
  - role: PromoteMurtogg
  - role: EnableRDP
  - role: PotatoPrivs
  - role: RebootComputer

- name: Launching Interceptor...
  hosts: interceptor
  gather_facts: true
  roles:
  - role: NukeDefender
  - role: Remove_All_Updates
  - role: DomainJoinInterceptor

- name: Promoting Mullroy on Interceptor
  hosts: admin-interceptor
  gather_facts: true
  roles:
  - role: PromoteMullroy
  - role: EnableRDP  